coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto

comment:
  layout: "reach, diff, flags, files"
  require_changes: false

ignore:
  - "tests/**"
  - "scripts/**"
  - "config/**"
