bucketName: rubintv_data

# Required items:
dimensionUniverseFile: /project/rubintv/butlerDimensionUniverse.json

# Summit items:
nightReportPath: /project/rubintv/nightReportData

# AuxTel
auxtelButlerPath: LATISS
auxTelMetadataPath: /project/rubintv/sidecar_metadata
auxTelMetadataShardPath: /project/rubintv/sidecar_metadata/shards

# all sky
allSkyRootDataPath: /project/rubintv/allsky/raw
allSkyOutputPath: /project/rubintv/allsky

# animation
moviePngPath: /project/rubintv/auxTel_animation

# Star Trackers paths:
# The path at which to find the data on disk. Does not include the
# GenericCamera/101/ or GenericCamera/102/ part, just the base directory.
starTrackerDataPath: /project
starTrackerOutputPath: /project/rubintv/starTracker/output
starTrackerMetadataPath: /project/rubintv/starTracker/sidecar_metadata
starTrackerMetadataShardPath: /project/rubintv/starTracker/sidecar_metadata/shards


# The path to the astrometry.net reference catalogs. Do not include
# the /4100 or /4200, just the base directory.
astrometryNetRefCatPath: /project/shared/ref_cats/astrometry_net

# ComCam configuration:
comCamButlerPath: /repo/LSSTComCam/butler.yaml
binning: 8
# # paths for serving TS8 metadata at SLAC
comCamMetadataPath: /project/rubintv/LSSTComCam/sidecar_metadata
comCamMetadataShardPath: /project/rubintv/LSSTComCam/sidecar_metadata/shards

comCamSimMetadataPath: /project/rubintv/LSSTComCamSim/sidecar_metadata
comCamSimMetadataShardPath: /project/rubintv/LSSTComCamSim/sidecar_metadata/shards

comCamSimAosMetadataPath: /project/rubintv/LSSTComCamSimAos/sidecar_metadata
comCamSimAosMetadataShardPath: /project/rubintv/LSSTComCamSimAos/sidecar_metadata/shards

comCamAosMetadataPath: /project/rubintv/LSSTComCamAos/sidecar_metadata
comCamAosMetadataShardPath: /project/rubintv/LSSTComCamAos/sidecar_metadata/shards

raPerformanceDirectory: /project/rubintv/raPerformance/sidecar_metadata
raPerformanceShardsDirectory: /project/rubintv/raPerformance/sidecar_metadata/shards

guiderDirectory: /project/rubintv/LSSTCam/guiders/sidecar_metadata
guiderShardsDirectory: /project/rubintv/LSSTCam/guiders/sidecar_metadata/shards

lsstCamMetadataPath: /project/rubintv/LSSTCam/sidecar_metadata
lsstCamMetadataShardPath: /project/rubintv/LSSTCam/sidecar_metadata/shards
lsstCamAosMetadataPath: /project/rubintv/LSSTCamAos/sidecar_metadata/shards
lsstCamAosMetadataShardPath: /project/rubintv/LSSTCamAos/sidecar_metadata/shards
lsstCamButlerPath: LSSTCam

# Not prefixed with ComCam because were currently just pretending that ComCam is TS8
scratchPath : rapidAnalysisScratch
plotPath: /project/rubintv/plots

# TMA config:
tmaMetadataPath: /project/rubintv/tma/sidecar_metadata
tmaMetadataShardPath: /project/rubintv/tma/sidecar_metadata/shards

consDBURL: "http://consdb-pq.consdb:8080/consdb"

aosLSSTCamPipelineFileDanish: $DONUT_VIZ_DIR/pipelines/production/lsstCamRapidAnalysisPipeline_Danish.yaml
aosLSSTCamPipelineFileTie: $DONUT_VIZ_DIR/pipelines/production/lsstCamRapidAnalysisPipeline_TIE.yaml
aosLSSTCamRefitWcsPipelineFile: $DONUT_VIZ_DIR/pipelines/production/lsstCamRapidAnalysisPipeline_RefitWcsDanish.yaml
aosLSSTCamAiDonutPipelineFile: $DONUT_VIZ_DIR/pipelines/production/lsstCamRapidAnalysisPipeline_AiDonut.yaml
aosLSSTCamTartsPipelineFile: $DONUT_VIZ_DIR/pipelines/production/lsstCamRapidAnalysisTartsUnpairedPipeline.yaml
aosLSSTCamUnpairedDanishPipelineFile: $DONUT_VIZ_DIR/pipelines/production/lsstCamRapidAnalysisPipeline_UnpairedDanish.yaml
aosLSSTCamWcsDanishPipelineFile: $DONUT_VIZ_DIR/pipelines/production/lsstCamRapidAnalysisPipeline_WcsCatDanish.yaml

aosLSSTCamFullArrayModePipelineFileDanish: $DONUT_VIZ_DIR/pipelines/production/lsstCamScienceSensorRapidAnalysisPipeline_Danish.yaml
aosLSSTCamFullArrayModePipelineFileTie: $DONUT_VIZ_DIR/pipelines/production/lsstCamScienceSensorRapidAnalysisPipeline_TIE.yaml

aosDataDir: /project/rubintv/aos_data

sfmPipelineFile:
  LATISS: $ATMOSPEC_DIR/pipelines/processStar.yaml
  LSSTComCamSim: $DRP_PIPE_DIR/pipelines/LSSTComCamSim/quickLook.yaml
  LSSTComCam: $DRP_PIPE_DIR/pipelines/LSSTComCam/quickLook.yaml
  LSSTCam: $DRP_PIPE_DIR/pipelines/LSSTCam/quickLook.yaml

outputChains:
  LATISS: LATISS/runs/quickLook
  LSSTComCam: LSSTComCam/runs/quickLook
  LSSTComCamSim: LSSTComCamSim/runs/quickLook
  LSSTCam: LSSTCam/runs/quickLook
